# Generated by CodiumAI

import pytest
from diffbot_kg.clients import DiffbotEnhanceClient, DiffbotSearchClient
from diffbot_kg.session import DiffbotResponse


class TestDiffbotSearchClient:
    @pytest.fixture(scope="class")
    def search_client(self):
        # trunk-ignore(bandit/B106)
        return DiffbotSearchClient(token="fake_token")

    # Returns a DiffbotResponse object when given a search query.
    @pytest.mark.asyncio
    async def test_mocked_search_query(self, mock, client):
        # Define the search query parameters
        params = {"query": "your_search_query", "limit": 10}

        # Mock the _post_or_put method
        mock.patch.object(
            DiffbotSearchClient,
            "_get_or_post",
            return_value=DiffbotResponse(200, {}, {}),  # type: ignore
        )

        # Call the search method
        response = await client.search(params)

        # Assert that the response is an instance of DiffbotResponse
        assert isinstance(response, DiffbotResponse)
        assert response.status == 200


class TestDiffbotEnhanceClient:
    @pytest.fixture(scope="class")
    def client(self):
        # trunk-ignore(bandit/B106)
        return DiffbotEnhanceClient(token="valid_token")

    # Returns a DiffbotResponse object when given an enhance query.
    @pytest.mark.asyncio
    async def test_mocked_enhance_query(self, mocker, client):
        # Define the search query parameters
        params = {"query": "your_search_query", "limit": 10}

        # Mock the _post_or_put method
        mocker.patch.object(
            DiffbotEnhanceClient,
            "_get",
            return_value=DiffbotResponse(200, {}, {}),  # type: ignore
        )

        # Call the search method
        response = await client.enhance(params)

        # Assert that the response is an instance of DiffbotResponse
        assert isinstance(response, DiffbotResponse)
        assert response.status == 200

    # Returns a DiffbotResponse object when given a bulk enhance query.
    @pytest.mark.asyncio
    async def test_mocked_create_bulkjob(self, mocker, client):
        # Define the search query parameters
        params = {"query": "your_bulk_enhance_query", "limit": 10}

        # Mock the _post_or_put method
        mocker.patch.object(
            DiffbotEnhanceClient,
            "_post",
            return_value=DiffbotResponse(200, {}, {}),  # type: ignore
        )

        # Call the bulk enhance method
        response = await client.create_bulkjob(params)

        # Assert that the response is an instance of DiffbotResponse
        assert isinstance(response, DiffbotResponse)
        assert response.status == 200
